version: '2'
services:
    web:
        build:
            context: ./web
            dockerfile: web.docker
        volumes:
            - ./web/www:/var/www
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./app
            dockerfile: app.docker
        volumes:
            - ./app/www:/var/www
    data:
        build:
            context: ./db
            dockerfile: db.docker
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - ./db/data:/var/lib/mysql   
        ports:
            - "3306:3306"
        